project_name: artransfer

env:
  - GO111MODULE=on
  - CGO_ENABLED=1

# build multi-platform
builds:
  ## Amd 64

  # Linux (amd_64)
  - id: linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    binary: "{{.ProjectName}}"
    main: ./main.go
    ldflags: &common_ldflags |
      -X github.com/ArtalkJS/Artransfer-CLI/lib.Version={{.Version}}
      -X github.com/ArtalkJS/Artransfer-CLI/lib.CommitHash={{ .ShortCommit }}
      -s -w

  # Windows (amd_64)
  - id: windows-amd64
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    binary: "{{.ProjectName}}"
    main: ./main.go
    ldflags: *common_ldflags

  # Darwin (amd_64)
  - id: darwin-amd64
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    binary: "{{.ProjectName}}"
    main: ./main.go
    ldflags: *common_ldflags
      
  ## Arm
  
  # Linux (arm_v7)
  - id: linux-armhf
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    env:
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
    binary: "{{.ProjectName}}"
    main: ./main.go
    ldflags: *common_ldflags

  # Linux (arm_64)
  - id: linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    binary: "{{.ProjectName}}"
    main: ./main.go
    ldflags: *common_ldflags

  # Darwin (arm_64)
  - id: darwin-arm64
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    binary: "{{.ProjectName}}"
    main: ./main.go
    ldflags: *common_ldflags

archives:
  - id: artransfer
    builds:
      - linux-amd64
      - darwin-amd64
      - windows-amd64
      - linux-armhf
      - linux-arm64
      - darwin-arm64
    name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}_{{.Arch}}{{.Arm}}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: false

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{.Version}}-SNAPSHOT-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: ArtalkJS
    name: Artransfer-CLI
  prerelease: auto
  draft: true
